#!/usr/bin/env python3
import skilstak.colors as c


print(c.y+ """Our characters arrive in a pickle, Tybalt has been killed by Juliets loved one Romeo. The happy and exciting story of these young
people has been grinded to a halt. With two already dead and maybe more to come help us decide where this will end and if the couple can make it out
alive.""")

print(c.y + """Juliett: See where she comes from shift with merry look. Capulet: Hey now my headstrong where have you have gadding? Juliet: Where
I have learned me to repent the sin of disobedient opposition, to you and your behests , and am enjoined by holy lawrence to fall postrate here to
beg your pardon. Pardon, I beseech you. Henceforth, I am ever ruled by you.
Capulet: Send for the county. Go tell him of this I'll have this knot knit up by tomorrow morning...
No, not till Thursday. There is time enough.
Go, nurse. Go with her. We'll to church tomorrow.(Lines 15-38, Act 4, Scene 2""")
