#!/usr/bin/env python3
import skilstak.colors as c


print(c.y+ """Our characters arrive in a pickle, Tybalt has been killed by Juliets loved one Romeo. The happy and exciting story of these young
people has been grinded to a halt. With two already dead and maybe more to come help us decide where this will end and if the couple can make it out
alive.""")

print(c.y + """Juliett: See where she comes from shift with merry look. Capulet: Hey now my headstrong where have you have gadding? Juliet: Where
I have learned me to repent the sin of disobedient opposition, to you and your behests , and am enjoined by holy lawrence to fall postrate here to
beg your pardon. Pardon, I beseech you. Henceforth, I am ever ruled by you.
Capulet: Send for the county. Go tell him of this I'll have this knot knit up by tomorrow morning...
No, not till Thursday. There is time enough.
Go, nurse. Go with her. We'll to church tomorrow. -Lines 15-38, Act 4, Scene 2""")

print(c.b + """You are Capulet in this situation, in this world though you have not yet made your choice to move up the day of your daughters
wedding, you want the best for her so you want her to be happy and married as soon as possible. Your judgement is also clouded because a member
of your family was just killed by a member of your enemys family. You want to get back the order from the chaos that world had lost. Do you think
it is best for you to act quickly and move the marriage forward with the intial plans to marry on Thursday--option A-- or ask Juliet when she wants to 
get married to Paris--option B--?""")

def ask(question):
    print(c.red + question + c.reset)
    answer = input("> " + c.base3).lower().strip()
    print(c.reset)
    return answer

first = ask("""Which do you choose?""")

if first in ['A','a']:
    firstsecond = ask("""The marriage is still on Thursday, Juliett is still going to use the potion to make her self sleep for two days.
But this time she was not as careful in how she performed this because the date was not as soon. He fear did not drive her to making extra
careful choies when planning her fake death. She drank the potion in a different way than she should have and it did not go down her system
properly. Because of this she was only asleep for one day and Juliet begins to wake up inside her tomb.

You are paying your repects to her while insdie the tomb when you here rumbling from inside. A young and refreshed Juliet emerges out. You decide
either to pay attention a little closer and see if she is really your daughter--option A--, or you grab the nearby shovel used to dig the fresh
grave above into knocking the dead one away--option B--?""")
    if firstsecond in ['A', 'a']:
        firstthird = ask("""You wait and to come to the conlcusion that your daughter is alive. After much interrogation, you make her tell you
everything that has happened with Romeo. You have the final choice of letting Juliet be happy at the cost of your own happiness by letting her
escape to Mantua with Romeo--option A--or keep her confined to the walls of her own Room with Paris for the rest of her life--option B--?
